module.exports = {
  title: 'Produktionsteknik & Ekonomi',
  themeConfig: {
    sidebarDepth: 0,
    sidebar: [
      ['/', 'Introduktion'],
      {
        title: 'Material- och produktionsstyrning',
        collapsable: true,
        children: [
          'IntroduktionM',
          'Planering',
          'Logistik',
          ['Material', 'Material- och produktionsstyrning - MPS'],
          ['MPS', 'MPS i praktiken'],
          'Samverkan',
          ['Delomraden', 'Delområden'],
          ['Mal', 'Mål'],
          'Ledtid',
          'Materialstyrning',
          ['Materialbestallning', 'Materialbeställning'],
          ['Order', 'Order- och lagerstyrd materialbeställning'],
          'Lagerstyrning',
          ['Motiv', 'Motiv till lager'],
          ['Bestallningspunktsystem', 'Beställningspunktsystem'],
          ['Ekonomisk', 'Ekonomisk partistorlek'],
          'Produktionsstyrning',
          ['Forutsattningar', 'Förutsättningar'],
          'Kapacitet',
          'Tidplaner',
          ['Belaggningsschema', 'Beläggningsschema',],
          'Ordersats',
          ['Datorstodda', 'Datorstödda styrsystem'],
          'Utveckling',
        ]
      },
      {
        title: 'Produktionsekonomi',
        children: [
          'Kunskap',
          ['Foretag', 'Företag'],
          'Intressenter',
          'Produktions',
          'Kunden',
          'Lonsamhet',
          'Intakterna',
          'Kostnaderna',
          'Kapital',
          'Partistorlek',
          'Maskinresurser',
          'KapacitetP',
          'Marknadsprognos',
          'Stillestandsstatistik',
          'Styrning',
          'Toleransgranser',
          'Malvarde',
          'Traditionell',
          'Malvardesstyrning',
          'Omstallning',
          'Principer',
          ['Funktionell', 'Funktionell verkstad'],
          ['Flodesgrupper', 'Flödesgrupper'],
          'Produktverkstad',
          'Parallella',
          ['5S', '5S och slöseri'],
          'Visualisering',
          ['VisualiseringV', 'Visualisering i verkstaden'],
          'Sloseri',
          'Genomloppstid',
          ['Fordelar', 'Fördelar med korta genomloppstider'],
          'Flexibilitet',
          'PlaneringP',
          ['Forbattrad', 'Förbättrad kvalitet'],
          'Minska',
          'Omstallningstid',
          'Kostnader',
          'Kapacitetsokning',
          ['Inre', 'Inre och yttre tid'],
          'Separera',
          'Omvandla',
          ['Genomforande', 'Genomförande'],
        ]
      }
    ]
  }
}